### Команда, позволяющая загрпузить медиа фаил

POST http://localhost:8080/media/bytes
Content-Type: image/jpeg

< bath.jpg

> {%
 client.global.set('mediaName', response.body.name);

 %}


### Команда, позволяющая загрпузить медиа фаил

POST http://localhost:8080/media/multipart
Content-Type: multipart/form-data; boundary=WebBoundary

--WebBoundary
Content-Disposition: form-data; name="file"; filename="leviafan.jpg"
Content-Type: image/jpeg

< leviafan.jpg
--WebBoundary--

### Команда, позволяющая загрпузить сразу несколько медиа фаилов

POST http://localhost:8080/media/multi-multipart
Content-Type: multipart/form-data; boundary=WebBoundary

--WebBoundary
Content-Disposition: form-data; name="files"; filename="javalog.jpg"
Content-Type: image/jpeg

< javalog.jpg
--WebBoundary
Content-Disposition: form-data; name="files"; filename="music.mp3"
Content-Type: audio/mpeg

< music.mp3
--WebBoundary--

### Команда, выводящая все фильмы

GET http://localhost:8080/films/getAll

### Команда, выводящая фильм по id

GET http://localhost:8080/films/getById?id=3

### Команда, производящая поиск фильмов по названию

GET http://localhost:8080/films/searchByName?text=coc

### Команда, производящая поиск фильмов по жанру

GET http://localhost:8080/films/searchByGenre?text=hor

### Команда, добавляющая новый фильм в список

POST http://localhost:8080/films/save
Content-Type: application/json

{
  "id": 0,
  "name": "Ирония судьбы, или С легким паром! ",
  "price": 150,
  "productionYear": 1975,
  "country": [
    "USSR"
  ],
  "genre": [
    "comedy",
    "melodrama"
  ],
  "rating": 8.2,
  "views": 450,
  "image":"bath.jpg"
}

### Команда, позволяющая изменить название и описание к фильму по заданному id

POST http://localhost:8080/films/save
Content-Type: application/json

{
  "id": 7,
  "name": "Левиафан",
  "price": 100,
  "productionYear": 2014,
  "country": [
    "Russia"
  ],
  "genre": [
    "drama"
  ],
  "rating": 6.9,
  "views": 120,
  "image": "leviafan.jpg"
}

### Команда, добавляющая фильм в корзину

POST http://localhost:8080/films/removeById?id=6

### Команда, возвращающая фильм из корзины

POST http://localhost:8080/films/restoreById?id=6

### Команда, позволяющая купить фильм (получить доступ к просмотру)

POST http://localhost:8080/sales/register
Content-Type: application/json

{
  "filmId": 3,
  "price": 200
}